//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nunit.org/webservices")]
[System.Xml.Serialization.XmlRootAttribute("Recording", Namespace="http://nunit.org/webservices", IsNullable=false)]
public partial class RecordingDto {
    
    private long idField;
    
    private string titleField;
    
    private string artistNameField;
    
    private string releaseDateField;
    
    private string labelNameField;
    
    private TrackDto[] tracksField;
    
    private ReviewDto[] reviewsField;
    
    private int totalRunTimeField;
    
    private bool totalRunTimeFieldSpecified;
    
    private int averageRatingField;
    
    private bool averageRatingFieldSpecified;
    
    /// <remarks/>
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string artistName {
        get {
            return this.artistNameField;
        }
        set {
            this.artistNameField = value;
        }
    }
    
    /// <remarks/>
    public string releaseDate {
        get {
            return this.releaseDateField;
        }
        set {
            this.releaseDateField = value;
        }
    }
    
    /// <remarks/>
    public string labelName {
        get {
            return this.labelNameField;
        }
        set {
            this.labelNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tracks")]
    public TrackDto[] tracks {
        get {
            return this.tracksField;
        }
        set {
            this.tracksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("reviews")]
    public ReviewDto[] reviews {
        get {
            return this.reviewsField;
        }
        set {
            this.reviewsField = value;
        }
    }
    
    /// <remarks/>
    public int totalRunTime {
        get {
            return this.totalRunTimeField;
        }
        set {
            this.totalRunTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool totalRunTimeSpecified {
        get {
            return this.totalRunTimeFieldSpecified;
        }
        set {
            this.totalRunTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int averageRating {
        get {
            return this.averageRatingField;
        }
        set {
            this.averageRatingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool averageRatingSpecified {
        get {
            return this.averageRatingFieldSpecified;
        }
        set {
            this.averageRatingFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nunit.org/webservices")]
public partial class TrackDto {
    
    private long idField;
    
    private string titleField;
    
    private string artistNameField;
    
    private int durationField;
    
    private string genreNameField;
    
    /// <remarks/>
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string artistName {
        get {
            return this.artistNameField;
        }
        set {
            this.artistNameField = value;
        }
    }
    
    /// <remarks/>
    public int duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    public string genreName {
        get {
            return this.genreNameField;
        }
        set {
            this.genreNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nunit.org/webservices")]
public partial class ReviewDto {
    
    private long idField;
    
    private string reviewerNameField;
    
    private int ratingField;
    
    private string reviewContentField;
    
    /// <remarks/>
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string reviewerName {
        get {
            return this.reviewerNameField;
        }
        set {
            this.reviewerNameField = value;
        }
    }
    
    /// <remarks/>
    public int rating {
        get {
            return this.ratingField;
        }
        set {
            this.ratingField = value;
        }
    }
    
    /// <remarks/>
    public string reviewContent {
        get {
            return this.reviewContentField;
        }
        set {
            this.reviewContentField = value;
        }
    }
}
